### PR TITLE
Fix/remodelled unit tests

### PR DESCRIPTION
**Pull request by sy238-unikent**
Large merge requests, mostly about unit tests.

With these changes, running:

``vendor/bin/phpunit --exclude media``

should successfully complete - although there are a couple of warnings, one failure and 334 incomplete tests...

This includes a lot of test stubs for apicommands.

For why media tests are excluded, see https://github.com/unikent/astro/issues/56

### CODE REVIEW

**Comment by cfc7-unikent** [comment]
I think I've fixed the failing unit test by adding in the parent_id to the valid data provider.
Is this the right thing? @sy238-unikent

**Comment by sy238-unikent** [comment]
i think that should work...

**Comment by sy238-unikent** [comment]
... are the tests passing for you now?

**Comment by cfc7-unikent** [comment]
@sy238-unikent yep :-) I'll merge it in

**Pull request merged**
