### PR TITLE
Fix/editor fixates on site id 1

### PR DESCRIPTION
**Pull request by sy238-unikent**
Please have a look at the single change I've made to Editor.vue which (I think!) updates the global state's site id value based on the current route.

Prior to this change, the editor would always load the site hierarchy / tree for site id 1, regardless of which site the user clicks on in the site list, despite loading the correct page to edit initially.

What is the "proper" way to update this value... or is this ok?

Also please ignore the AddSite and AddUser files i have accidentally included in this merge request...

many cheers!

### CODE REVIEW

**Comment by sy238-unikent** [comment]
Christian said (via email):

> Not sure if you’ve got a reply from Jack but what I think you are missing is a mutation for the value.
> Have a look at https://vuex.vuejs.org/en/mutations.html
>  
> You can see what in that Editor file where I am commiting a change to the store in the updateCurrentSavedState method.
>  
> As I understand it each time you want to change/store a value in the vuex store you need to have a mutation (basically a setter) and ‘commit’ that.

**Comment by sy238-unikent** [comment]
@cfc7-unikent I have made some modifications to (hopefully) use a mutation correctly instead.

Please review :)

**Comment by cfc7-unikent** [comment]
Site variable stuff looks good :-) 💯 

_I can't add other sites yet - I'm assuming an issue with my home setup or we've just not got to that bit yet_

Any chance of removing AddSite.php and AddUser.php from the pull request? (my git foo is not good enough to suggest how to do that however without the effort of starting again at develop and then adding in the updated vue files ...)

**Comment by sy238-unikent** [comment]
I have clunkily removed those files and committed again.

**Comment by cfc7-unikent** [comment]
I think this will be fine. I tested this this morning without the two Add* files. But I can't seem to merge this in via the web. I'm getting errors about conflicts 
conflicts

**Comment by sy238-unikent** [comment]
Closed - see #62 instead.

**Pull request closed without merging**
